# Generated by Django 5.0 on 2026-01-12 06:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLogModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changes", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_logs",
            },
        ),
    ]
