# Generated by Django 5.0 on 2026-01-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="approval_chain",
            field=models.JSONField(
                default=dict, help_text="Approval chain configuration"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="approval_required",
            field=models.BooleanField(default=False, help_text="Is approval required?"),
        ),
        migrations.AddField(
            model_name="contract",
            name="current_approvers",
            field=models.JSONField(default=list, help_text="Current approvers"),
        ),
        migrations.AddField(
            model_name="contract",
            name="description",
            field=models.TextField(
                blank=True, help_text="Contract description", null=True
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="document_r2_key",
            field=models.CharField(
                blank=True,
                help_text="R2 storage key for document",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="last_edited_at",
            field=models.DateTimeField(
                blank=True, help_text="Last edited timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="last_edited_by",
            field=models.UUIDField(
                blank=True, help_text="User ID who last edited", null=True
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="metadata",
            field=models.JSONField(default=dict, help_text="Additional metadata"),
        ),
    ]
