# Generated by Django 5.0 on 2026-02-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_expand_firma_status_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmasigningauditlog',
            name='event',
            field=models.CharField(choices=[('upload', 'Document Uploaded'), ('invite_sent', 'Invitation Sent'), ('status_checked', 'Status Checked'), ('document_downloaded', 'Document Downloaded'), ('webhook', 'Webhook Event'), ('reminder', 'Reminder'), ('error', 'Error')], db_index=True, max_length=50),
        ),
    ]
