# Generated by Django 5.0 on 2026-01-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_user_login_otp_user_otp_attempts_user_otp_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="user",
            table="clm_users",
        ),
    ]
