from __future__ import annotations

CONSTRAINT_LIBRARY: list[dict] = [
    {"key": "governing_law", "label": "Governing Law", "category": "Legal", "default": "California"},
    {"key": "venue", "label": "Venue", "category": "Legal", "default": "San Francisco County, CA"},
    {"key": "jurisdiction", "label": "Jurisdiction", "category": "Legal", "default": "State or Federal courts in California"},
    {"key": "notice_period_days", "label": "Notice Period (days)", "category": "Notices", "default": "30"},
    {"key": "cure_period_days", "label": "Cure Period (days)", "category": "Termination", "default": "15"},
    {"key": "payment_terms", "label": "Payment Terms", "category": "Commercial", "default": "Net 30"},
    {"key": "late_fee", "label": "Late Fee", "category": "Commercial", "default": "1.5% per month"},
    {"key": "currency", "label": "Currency", "category": "Commercial", "default": "USD"},
    {"key": "auto_renew", "label": "Auto-Renewal", "category": "Term", "default": "No"},
    {"key": "initial_term_months", "label": "Initial Term (months)", "category": "Term", "default": "12"},
    {"key": "renewal_term_months", "label": "Renewal Term (months)", "category": "Term", "default": "12"},
    {"key": "confidentiality_term_years", "label": "Confidentiality Term (years)", "category": "Confidentiality", "default": "3"},
    {"key": "residuals", "label": "Residuals", "category": "Confidentiality", "default": "Not permitted"},
    {"key": "data_residency", "label": "Data Residency", "category": "Data", "default": "US"},
    {"key": "subprocessors", "label": "Subprocessors", "category": "Data", "default": "Allowed with notice"},
    {"key": "security_standard", "label": "Security Standard", "category": "Security", "default": "Reasonable industry standard"},
    {"key": "incident_notification_hours", "label": "Incident Notification (hours)", "category": "Security", "default": "72"},
    {"key": "audit_rights", "label": "Audit Rights", "category": "Security", "default": "Annual upon reasonable notice"},
    {"key": "ip_ownership", "label": "IP Ownership", "category": "IP", "default": "Each party retains its pre-existing IP"},
    {"key": "work_product_ownership", "label": "Work Product Ownership", "category": "IP", "default": "Client owns deliverables upon payment"},
    {"key": "license_grant", "label": "License Grant", "category": "IP", "default": "Non-exclusive, non-transferable"},
    {"key": "sla_uptime", "label": "SLA Uptime", "category": "SLA", "default": "99.9%"},
    {"key": "support_hours", "label": "Support Hours", "category": "SLA", "default": "Business hours"},
    {"key": "response_time", "label": "Response Time", "category": "SLA", "default": "1 business day"},
    {"key": "liability_cap", "label": "Liability Cap", "category": "Liability", "default": "Fees paid in prior 12 months"},
    {"key": "liability_exclusions", "label": "Liability Exclusions", "category": "Liability", "default": "Indirect / consequential damages excluded"},
    {"key": "indemnity", "label": "Indemnity", "category": "Risk", "default": "Mutual (IP infringement only)"},
    {"key": "insurance", "label": "Insurance", "category": "Risk", "default": "Commercial general liability required"},
    {"key": "assignment", "label": "Assignment", "category": "Misc", "default": "No assignment without consent"},
    {"key": "subcontracting", "label": "Subcontracting", "category": "Misc", "default": "Allowed with responsibility retained"},
    {"key": "non_solicit_term_months", "label": "Non-Solicit Term (months)", "category": "Employment", "default": "12"},
    {"key": "non_compete", "label": "Non-Compete", "category": "Employment", "default": "Not included"},
    {"key": "non_disparagement", "label": "Non-Disparagement", "category": "Employment", "default": "Mutual"},
    {"key": "change_control", "label": "Change Control", "category": "Delivery", "default": "Written change orders required"},
    {"key": "acceptance_criteria", "label": "Acceptance Criteria", "category": "Delivery", "default": "Deemed accepted after 10 days"},
    {"key": "deliverable_schedule", "label": "Deliverable Schedule", "category": "Delivery", "default": "Milestone-based"},
    {"key": "termination_for_convenience", "label": "Termination for Convenience", "category": "Termination", "default": "30 days notice"},
    {"key": "termination_for_cause", "label": "Termination for Cause", "category": "Termination", "default": "Material breach with cure"},
    {"key": "force_majeure", "label": "Force Majeure", "category": "Misc", "default": "Standard"},
    {"key": "export_controls", "label": "Export Controls", "category": "Compliance", "default": "Comply with applicable laws"},
]
