# Generated by Django 5.0 on 2026-01-12 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchIndexModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.UUIDField()),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("keywords", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "search_indices",
            },
        ),
    ]
