# Generated by Django 5.0 on 2026-01-12 08:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchAnalyticsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("query", models.CharField(max_length=255)),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("full_text", "Full-Text"),
                            ("semantic", "Semantic"),
                            ("hybrid", "Hybrid"),
                            ("faceted", "Faceted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("results_count", models.IntegerField(default=0)),
                ("response_time_ms", models.IntegerField(default=0)),
                ("clicked_result_id", models.UUIDField(blank=True, null=True)),
                (
                    "clicked_result_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "search_analytics",
            },
        ),
        migrations.AddField(
            model_name="searchindexmodel",
            name="indexed_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="searchindexmodel",
            name="metadata",
            field=models.JSONField(
                default=dict, help_text="Additional metadata for filtering"
            ),
        ),
        migrations.AddField(
            model_name="searchindexmodel",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="searchindexmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="searchindexmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="searchindexmodel",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("contract", "Contract"),
                    ("template", "Template"),
                    ("workflow", "Workflow"),
                    ("document", "Document"),
                    ("approval", "Approval"),
                    ("audit_log", "Audit Log"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="searchindexmodel",
            name="keywords",
            field=models.JSONField(
                default=list, help_text="Array of searchable keywords"
            ),
        ),
        migrations.AlterField(
            model_name="searchindexmodel",
            name="tenant_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="searchindexmodel",
            name="title",
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="searchindexmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="search_index_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="searchindexmodel",
            index=models.Index(
                fields=["tenant_id", "entity_type"], name="tenant_entity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchindexmodel",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="entity_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchanalyticsmodel",
            index=models.Index(
                fields=["tenant_id", "created_at"], name="search_analytics_tenant_date"
            ),
        ),
        migrations.AddIndex(
            model_name="searchanalyticsmodel",
            index=models.Index(fields=["query_type"], name="search_analytics_type"),
        ),
    ]
