# Generated by Django 5.0 on 2026-01-12 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RuleModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("workflow", "Workflow"),
                            ("validation", "Validation"),
                            ("automation", "Automation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("conditions", models.JSONField(default=dict)),
                ("actions", models.JSONField(default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rules",
            },
        ),
    ]
